### ISSUE TITLE
Notes from Eric

### ISSUE THREAD

**Issue by sckott** [ropensci/opencontext#2]
The new version deployed in 
- http://146.148.79.138/sets/
- http://opencontext.dainst.org/sets/

Other: 
- http://opencontext.dainst.org/about/services
- http://opencontext.dainst.org/about/recipes

**Comment by sckott** [comment]
more notes:

The new API is GeoJSON + JSON-LD. Also the main structured data representation in Open Context is moving to JSON-LD (plus GeoJSON for most items). Like the original API, you just add ".json" to the URLs to get the JSON-LD data. It also now supports content negotiation. Background is here: https://github.com/ekansa/open-context-py/blob/master/docs/search-api.md

To get to animal bones in Turkey: 

http://146.148.79.138/sets/Turkey?prop=oc-gen-cat-animal-bone&geodeep=10

There will be facets with linked data, including common anatomical measurements:
http://146.148.79.138/sets/Turkey?geodeep=10&prop=oc-gen-cat-animal-bone&prop=oc-zoo-anatomical-meas---oc-zoo-von-den-driesch-bone-meas

I don't have a user interface that does anything with the measurements yet, but you play with them via the API:
http://146.148.79.138/sets/Turkey.json?geodeep=10&prop=oc-gen-cat-animal-bone&prop=oc-zoo-anatomical-meas---oc-zoo-von-den-driesch-bone-meas

The following has numeric facet ranges for the Von den Driesch "Bd" (breadth of the distal end) measurement: 
http://146.148.79.138/sets/Turkey.json?geodeep=10&prop=oc-gen-cat-animal-bone&prop=oc-zoo-anatomical-meas---oc-zoo-von-den-driesch-bone-meas---oc-zoo-bd

It's not terribly meaningful until you narrow by element and taxa (humerus and ovis below):
http://146.148.79.138/sets/Turkey.json?geodeep=10&prop=oc-gen-cat-animal-bone&prop=oc-zoo-anatomical-meas---oc-zoo-von-den-driesch-bone-meas---oc-zoo-bd&prop=oc-zoo-has-anat-id---obo-uberon-0000976&prop=biol-term-hastaxonomy---eol-p-1---eol-p-1642---eol-p-7678---eol-p-7687---eol-p-39510

In the query above, you see a list of numeric range facets in "oc-api:has-numeric-facets". Those will give links to further query the data, but they can also be used to make some nice histogram plots.

You're probably going to want to get to individual records of the bones in Turkey. To limit an API request for individual records only, add a "&response=geo-record" or "&response=uri-meta" (or "&response=uri" if you only want a list of URIs from a search). Adding a "&row=" parameter lets you ask for more (or less) than the default 20 records. The URIs to individual records can be followed to get all the attribute data on a record, with a caveat. To use the nice new GeoJSON-LD representation, you'll have to substitute "http://opencontext.org/" for "http://146.148.79.138/". Add a ".json" or do content negotiation to get the JSON data for each record.

**Comment by ekansa** [comment]
Small typo in the note above. The URL parameter for getting more rows is "rows" not "rows".

**Comment by sckott** [comment]
Thanks

**Comment by ekansa** [comment]
A few more points before I get on my plane (no time to update the "official API docs"). The faceted search service will only return project-specific descriptive properties / predicates after you've already filtered by one or more projects.

Also, there seems to be a bug in returning general item types / classification. To get these facets, add the "type=subjects" to a query.

Thanks!

**Comment by benmarwick** [comment]
I've got a few sketches of getting data with these URLs here: https://gist.github.com/benmarwick/50aa4c39b7d955d0ec40

Here's the article that I think it would be good to use as a test case for getting data from OC: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0099845

**Comment by benmarwick** [comment]
```
library(dplyr)
library(httr)
library(jsonlite)

# helper function for GET
oc_GET <- function(url, args, ...){
  res <- GET(url, query=args, ...)
  stop_for_status(res)
  content(res, "text")
}

# base URL for OpenContext
oc_base <- function() "http://146.148.79.138/"

# get list of countries
sets <- paste0(oc_base(), "sets/", ".json") %>%
 oc_GET(list()) %>%
  fromJSON

countries <- sets$`oc-api:has-facets`$`oc-api:has-id-options`[[1]]

projects <- sets$`oc-api:has-facets`$`oc-api:has-id-options`[[3]]
```
