### ISSUE TITLE
More notes on Open Context

### ISSUE THREAD

**Issue by ekansa** [ropensci/opencontext#3]
The new API is deployed on a new version of Open Context. We migrated data from the previous version of Open Context (still deployed at http://opencontext.org). We are still trouble shooting and fixing issues associated with migrating to a new schema, so there will likely be some "noise" in the data at the new site that we still need to resolve.

If you find problems, please help by sharing issues on the issue tracker in this repo or our project repo: https://github.com/ekansa/open-context-py

Thanks!

**Comment by sckott** [comment]
Sounds good. Thanks @ekansa will put issues in that repo
