### ISSUE TITLE
Open Context API changes

### ISSUE THREAD

**Issue by ekansa** [ropensci/opencontext#4]
Hi All,

I've turned off the old version of Open Context and turned on the new version. I made some small changes to the API. The only change that impacts this project is that the APIs have different URLs:

Open Context has a variety of query services for different types of content. These all use the same query syntax and, if desired, will return JSON using the same schema. The different query services are as follows:
- Data Records ('subjects'): For searching the subjects of observation and recording (the main 'data' in Open Context, start search requests with the following URL:
  http://opencontext.org/subjects-search/
- Media Resources: For searching metadata about media (images, videos, and other binary media formats) in Open Context, start search requests with the following URL:
  http://opencontext.org/media-search/
- Projects: For searching project metadata and abstracts in Open Context, start search requests with the following URL:
  http://opencontext.org/projects-search/
- Everything: For all inclusive searches of all content types in Open Context, start search requests with the following URL:
  http://opencontext.org/search/

See the documentation over at: http://opencontext.org/about/services

**Comment by sckott** [comment]
Thanks @ekansa ! The new API looks good :+1:
